name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths:
      - 'docs/**'
      - '**.md'

jobs:
  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check documentation files
        run: |
          echo "Checking documentation structure..."
          test -f README.md && echo "✓ README.md exists" || echo "✗ README.md missing"
          test -f LICENSE && echo "✓ LICENSE exists" || echo "✗ LICENSE missing"
          test -d docs && echo "✓ docs/ directory exists" || echo "✗ docs/ directory missing"
      
      - name: Check for broken links
        run: |
          echo "Checking markdown files..."
          find . -name "*.md" -type f | while read file; do
            echo "Checking $file"
            test -f "$file" && echo "✓ $file is valid" || echo "✗ $file has issues"
          done
      
      - name: Count documentation
        run: |
          echo "Documentation statistics:"
          echo "Markdown files:"
          find . -name "*.md" -type f | wc -l
          echo "Total documentation lines:"
          find . -name "*.md" -type f -exec wc -l {} + | tail -1 || echo "0 total"
