name: Performance Tests

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  performance:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      
      - name: Placeholder for performance tests
        run: |
          echo "Performance tests not yet implemented"
          echo "This workflow is disabled until test infrastructure is ready"
