name: Test Suite

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  lua-tests:
    name: Lua Backend Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install Busted
      run: luarocks install busted

    - name: Run Lua Test Suite (Busted BDD)
      run: |
        busted tests/test_story.lua \
               tests/test_compact_integration.lua \
               tests/test_rijks_load.lua \
               tests/test_renderer.lua \
               tests/test_validator.lua \
               tests/test_profiler.lua \
               tests/test_debugger.lua \
               tests/test_metatable_preservation.lua \
               tests/test_save_system.lua \
               tests/test_template_processor.lua \
               tests/test_harlowe_converter.lua \
               tests/test_sugarcube_converter.lua \
               tests/test_chapbook_converter.lua \
               tests/test_snowman_converter.lua \
               tests/test_format_converter.lua \
               tests/test_import.lua \
               tests/test_export.lua \
               tests/test_compact_format.lua \
               tests/test_harlowe_parser.lua \
               tests/test_sugarcube_parser.lua \
               tests/test_chapbook_parser.lua \
               tests/test_snowman_parser.lua \
               tests/test_converter_roundtrip.lua \
               tests/test_event_system.lua \
               tests/test_string_utils.lua

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: lua-test-results
        path: tests/test_report.txt
        if-no-files-found: ignore

  javascript-tests:
    name: JavaScript Editor Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test

    - name: Run Jest with coverage
      run: npm run test:coverage

    - name: Upload coverage reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: coverage/
        if-no-files-found: ignore

  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.4"

    - name: Install LuaRocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install luacheck
      run: luarocks install luacheck

    - name: Run luacheck
      run: luacheck lib/whisker/ tests/ --config .luacheckrc || echo "Luacheck completed with warnings"
      continue-on-error: true
